name: MarbleBaseMD
main: me.pattrick.marbledrop.Main
version: 1.0
api-version: 1.21
commands:
   md:
      description: Base command for marble drop
      usage: /md
   dust:
      description: Show Marble Dust balance or infuse dust into a marble
      usage: /dust [infuse <amount>]
   tasks:
      description: View and claim daily/weekly tasks
      usage: /tasks [claim]
   tasksadmin:
      description: Admin tools for tasks
      usage: /tasksadmin reset <daily|weekly|all> <player|all>
   infusiontable:
      description: Manage infusion table cauldrons
      usage: /infusiontable add|remove|count
      permission: marbledrop.admin
   dustadmin:
      description: Admin command to manage Marble Dust
      usage: /dustadmin <give|remove|set> <player> <amount>
      permission: marbledrop.admin.dust

permissions:
   marbledrop.admin:
      default: op