name: MarbleBaseMD
main: me.pattrick.marbledrop.Main
version: 1.0
api-version: 1.21
commands:
   md:
      description: Base command for marble drop
      usage: /md

permissions:
   marbledrop.admin:
      default: op
   marbledrop.infusion.bypass:
      description: Bypass daily infusion limits
      default: op